# Generated by scripts/generate-research-contracts.py; do not edit.
# Authoritative schema digest: 6745a7bacca1cd3a6ab9967778efcafd8cee59c52a09705ea8749bdc6f78d89d
from __future__ import annotations

from typing import Literal, NotRequired, TypedDict

ScientificClassification = Literal["pass", "fail", "unresolved", "not-evaluated"]
TechnicalState = Literal["draft", "validated", "prepared", "running", "completed", "cancelled", "interrupted", "failed", "analyzed", "archived"]
EventStage = Literal["prepare", "run", "analyze", "report", "runtime"]

class ResearchEvent(TypedDict):
    schema_version: Literal["research-event-v1"]
    sequence: int
    timestamp: str
    type: str
    stage: EventStage
    payload: dict[str, object]

class ArtifactRecord(TypedDict, total=False):
    id: str
    kind: str
    path: str
    sha256: str
    size: int
    media_type: str
    source_ids: list[str]

class ResearchConfig(TypedDict):
    schema_version: Literal["research-experiment-v1"]
    experiment_id: Literal["fixture.synthetic.v1", "e01-charged-branch"]
    model_id: Literal["fixture.deterministic-recurrence.v1", "charged-scalar-3d-v1"]
    parameters: dict[str, object]
    units: dict[str, str]
    seeds: dict[str, int]
    resources: dict[str, object]
    analysis: dict[str, object]
    report: dict[str, object]
    fixture_controls: NotRequired[dict[str, int | None]]
