#!/usr/bin/env python3
"""Generate small language boundary types from the authoritative schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

PYTHON = '''# Generated by scripts/generate-research-contracts.py; do not edit.
# Authoritative schema digest: __SCHEMA_DIGEST__
from __future__ import annotations

from typing import Literal, NotRequired, TypedDict

ScientificClassification = Literal["pass", "fail", "unresolved", "not-evaluated"]
TechnicalState = Literal["draft", "validated", "prepared", "running", "completed", "cancelled", "interrupted", "failed", "analyzed", "archived"]
EventStage = Literal["prepare", "run", "analyze", "report", "runtime"]

class ResearchEvent(TypedDict):
    schema_version: Literal["research-event-v1"]
    sequence: int
    timestamp: str
    type: str
    stage: EventStage
    payload: dict[str, object]

class ArtifactRecord(TypedDict, total=False):
    id: str
    kind: str
    path: str
    sha256: str
    size: int
    media_type: str
    source_ids: list[str]

class ResearchConfig(TypedDict):
    schema_version: Literal["research-experiment-v1"]
    experiment_id: Literal["fixture.synthetic.v1"]
    model_id: Literal["fixture.deterministic-recurrence.v1"]
    parameters: dict[str, object]
    units: dict[str, str]
    seeds: dict[str, int]
    resources: dict[str, object]
    analysis: dict[str, object]
    report: dict[str, object]
    fixture_controls: NotRequired[dict[str, int | None]]
'''

TYPESCRIPT = '''// Generated by scripts/generate-research-contracts.py; do not edit.
// Authoritative schema digest: __SCHEMA_DIGEST__
export type ScientificClassification =
  'pass' | 'fail' | 'unresolved' | 'not-evaluated';
export type TechnicalState =
  | 'draft'
  | 'validated'
  | 'prepared'
  | 'running'
  | 'completed'
  | 'cancelled'
  | 'interrupted'
  | 'failed'
  | 'analyzed'
  | 'archived';
export type EventStage = 'prepare' | 'run' | 'analyze' | 'report' | 'runtime';
export interface ResearchEvent {
  schema_version: 'research-event-v1';
  sequence: number;
  timestamp: string;
  type: string;
  stage: EventStage;
  payload: Record<string, unknown>;
}
export interface ArtifactRecord {
  id: string;
  kind: string;
  path: string;
  sha256: string;
  size: number;
  media_type: string;
  source_ids?: string[];
}
export interface ResearchConfig {
  schema_version: 'research-experiment-v1';
  experiment_id: 'fixture.synthetic.v1';
  model_id: 'fixture.deterministic-recurrence.v1';
  parameters: Record<string, unknown>;
  units: Record<string, string>;
  seeds: { root: number };
  resources: Record<string, number>;
  analysis: Record<string, number | boolean>;
  report: { title: string };
  fixture_controls?: {
    interrupt_at_step?: number | null;
    fail_at_step?: number | null;
  };
}
'''

OUTPUTS = {
    ROOT / "python/signal_space/contracts/generated.py": PYTHON,
    ROOT / "packages/research-contracts/src/generated.ts": TYPESCRIPT,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schemas = ROOT / "contracts/research"
    expected = {
        "experiment.schema.json": "Signal Space research experiment configuration",
        "run-manifest.schema.json": "Signal Space research run manifest",
        "event.schema.json": "Signal Space research event",
        "artifact.schema.json": "Signal Space research artifact",
    }
    schema_values = {}
    for name, title in expected.items():
        value = json.loads((schemas / name).read_text())
        schema_values[name] = value
        if value.get("$schema") != "https://json-schema.org/draft/2020-12/schema" or value.get("title") != title:
            raise SystemExit(f"Invalid authoritative schema metadata: {name}")
    digest = hashlib.sha256(
        json.dumps(schema_values, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    stale: list[str] = []
    for path, content in OUTPUTS.items():
        content = content.replace("__SCHEMA_DIGEST__", digest)
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Generated research contracts are stale: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
