#!/usr/bin/env python3
"""Run the locked Test 8 quiet prerequisite and prepare paired PR ZIPs.

The checkout must be clean. All generated bytes live in a new sibling output
directory and are never committed automatically. A scientific failure still
produces a complete evidence handoff when the pipeline technically completes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPERIMENT = 'gross.two-object-quiet-calibration.v1'


def sha(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def command(*args):
    subprocess.run(args, cwd=ROOT, check=True)


def pack(folder, output):
    if output.exists():
        raise ValueError(f'archive already exists; preserve its identity: {output}')
    temporary = output.with_suffix('.zip.tmp')
    if temporary.exists():
        raise ValueError(f'partial archive exists; inspect it first: {temporary}')
    try:
        with zipfile.ZipFile(temporary, 'x', compression=zipfile.ZIP_DEFLATED,
                             compresslevel=6, allowZip64=True) as bundle:
            for file in sorted(folder.rglob('*')):
                if file.is_file():
                    bundle.write(file, (Path(folder.name) / file.relative_to(folder)).as_posix())
        with zipfile.ZipFile(temporary) as bundle:
            bad = bundle.testzip()
            if bad:
                raise ValueError(f'ZIP failed CRC validation: {bad}')
        temporary.rename(output)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise
    return {'name': output.name, 'size_bytes': output.stat().st_size, 'sha256': sha(output)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path,
                        help='new output directory outside the checkout')
    parser.add_argument('--package-only', action='store_true',
                        help='verify and ZIP a previously completed output without rerunning physics')
    parser.add_argument("--threads", type=int, default=1)
    parser.add_argument("--case-jobs", type=int, default=1)
    args = parser.parse_args()
    output = args.output.resolve()
    if output.is_relative_to(ROOT):
        parser.error('output must be outside the Git checkout')
    if args.package_only:
        if not output.is_dir():
            parser.error('package-only requires a completed output directory')
    else:
        if output.exists():
            parser.error('a fresh run requires a new output directory')
        command(sys.executable, str(ROOT / '.agents/scripts/run_experiment.py'),
                '--experiment', 'gross-test-08-quiet', '--output', str(output),
                '--threads', str(args.threads), '--case-jobs', str(args.case_jobs))

    evidence, reader = output / 'evidence', output / 'reader'
    status = json.loads((evidence / 'status.json').read_text())
    if status['technical_status'] != 'completed' or status['experiment'] != 'gross-test-08-quiet':
        raise ValueError('pipeline is incomplete; preserve evidence and inspect its logs')
    source_run = evidence / status['canonical_path']
    index = json.loads((evidence / 'evidence-index.json').read_text())
    for row in index['files']:
        path = evidence / row['path']
        if not path.is_file() or sha(path) != row['sha256']:
            raise ValueError(f"outer evidence checksum mismatch: {row['path']}")
    env = {'PYTHONPATH': str(ROOT / 'src')}
    import os
    subprocess.run([sys.executable, '-m', 'signal_space', '--workspace', str(evidence / 'runs'),
                    'verify', '--run-id', status['run_id']], cwd=ROOT,
                   env={**os.environ, **env}, check=True)
    command(sys.executable, str(ROOT / '.agents/scripts/experiment_contract.py'),
            'bundle', str(reader), '--source-run', str(source_run))
    export = json.loads((reader / 'export.json').read_text())
    identity = export['source_run']
    if identity['experiment_id'] != EXPERIMENT or identity['run_id'] != status['run_id']:
        raise ValueError('reader is not paired with the canonical run')
    zip_evidence = pack(evidence, output / f'test8-quiet-evidence-{status["run_id"]}.zip')
    zip_reader = pack(reader, output / f'test8-quiet-reader-{status["run_id"]}.zip')
    manifest = source_run / 'manifest.json'
    index_file = output / 'pr-evidence-index.json'
    index_file.write_text(json.dumps({
        'experiment_id': EXPERIMENT,
        'scope': 'six-period calibration prerequisite; full Test 8 G0–G9 not assessed',
        'source_commit': status['source_commit'],
        'plan_lock': json.loads((evidence / 'plan.json').read_text())['locked_sha256'],
        'run_id': status['run_id'], 'analysis_id': status['analysis_id'],
        'report_id': status['report_id'],
        'technical_status': status['technical_status'],
        'scientific_classification': status['scientific_classification'],
        'canonical_manifest_sha256': sha(manifest),
        'checks': {row['id']: row['status'] for row in status['checks']},
        'archives': [zip_evidence, zip_reader],
    }, indent=2) + '\n')
    print(f'Completed local handoff: {output}')
    print(f'Classification: {status["scientific_classification"]}; run: {status["run_id"]}')
    print('Keep both ZIPs and pr-evidence-index.json together in the results PR.')
    return 0


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f'Test 8 local handoff stopped: {error}', file=sys.stderr)
        raise SystemExit(1)
