// Generated by scripts/generate-research-contracts.py; do not edit.
// Authoritative schema digest: 145e6c9b0a995a888365eef029131696fb25c7a0ee54ede32bb8283c5fb85efb
export type ScientificClassification =
  'pass' | 'fail' | 'unresolved' | 'not-evaluated';
export type TechnicalState =
  | 'draft'
  | 'validated'
  | 'prepared'
  | 'running'
  | 'completed'
  | 'cancelled'
  | 'interrupted'
  | 'failed'
  | 'analyzed'
  | 'archived';
export type EventStage = 'prepare' | 'run' | 'analyze' | 'report' | 'runtime';
export interface ResearchEvent {
  schema_version: 'research-event-v1';
  sequence: number;
  timestamp: string;
  type: string;
  stage: EventStage;
  payload: Record<string, unknown>;
}
export interface ArtifactRecord {
  id: string;
  kind: string;
  path: string;
  sha256: string;
  size: number;
  media_type: string;
  source_ids?: string[];
}
export interface ResearchConfig {
  schema_version: 'research-experiment-v1';
  experiment_id: 'fixture.synthetic.v1' | 'e01-charged-branch';
  model_id: 'fixture.deterministic-recurrence.v1' | 'charged-scalar-3d-v1';
  parameters: Record<string, unknown>;
  units: Record<string, string>;
  seeds: { root: number };
  resources: Record<string, number>;
  analysis: Record<string, number | boolean>;
  report: { title: string };
  fixture_controls?: {
    interrupt_at_step?: number | null;
    fail_at_step?: number | null;
  };
}
